---

  - name: Create Directory For Backend 
    file: 
      path: ~/app
      state: directory 

  - name: "Copy files"
    unarchive: 
      src: /root/project/artifact.tar.gz
      dest: ~/app
  
  - name: "Installing Node dependencies"
    shell:  |
      cd ~/app
      ls 
      npm i

  - name: "Executing Node with PM2"
    shell:  |
      cd ~/app/dist
      pm2 stop default
      pm2 start main.js 
    register: execute_node

  - name: "print message"
    debug:
      msg: {{execute_node.stdout_lines}}

  - name: "Add Pm2 as startup service"
    become: true
    shell: |
      env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
